### ISSUE TITLE
EmailAddress cannot longer than 253bytes？

### ISSUE THREAD

**Issue by zsy1217** [playframework/play-mailer#129] opened 2017-06-26 09:17 UTC
when i try sending mail to 255 bytes mail address. like "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeesample1@sample.com"
then error has occured ↓
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 553 5.1.0 <eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeesample1@sample.co... Address "<eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeesample1@sample.co" too long (255 bytes max)

is that bug?

**Comment by schmitch** [comment] 2017-06-26 09:21
can you please give a little bit more info about the issue?

**Comment by zsy1217** [comment] 2017-06-26 09:28
i added the information

**Comment by schmitch** [comment] 2017-06-26 09:28
No that is correct according to the spec, so closing as not a bug:
https://tools.ietf.org/html/rfc3696#section-3

**Closed by schmitch** 2017-06-26 09:28 UTC

**Comment by zsy1217** [comment] 2017-06-26 09:58
ummm  i tried [63byteuser]@[191bytedomain] which comply with the above rules 
 but the same error still occured.
